version: '3.4'

networks:
  microservice-net:
    driver: bridge

volumes:
  db_data: {}

services:
  database-mysql:
    image: mysql/mysql-server
    container_name: 'database-mysql'
    hostname: 'database-mysql'
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - microservice-net
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db_data/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
    expose:
      - '3306'
            
  onborading:
    image: ${DOCKER_REGISTRY-}onborading
    networks:
      - microservice-net
    hostname: onborading
    build:
      context: .
      dockerfile: OnBoarding.api/Dockerfile
    ports:
      - '49154:80'
    environment:
        LOG_LEVEL: debug
        ASPNETCORE_ENVIRONMENT: Development
        ConnectionStrings__DefaultConnection: 'server=database-mysql;port=3306;database=OnboardingAPIdb;user=root;password=password'
    depends_on:
       - database-mysql
            
  