networks:
  microservice-net:
    driver: bridge

volumes:
  db_data: {}

services:
  database-mysql:
    image: mysql/mysql-server
    container_name: 'database-mysql'
    networks:
      - microservice-net
    volumes:
      - db_data:/var/lib/mysql
      - ./db_data/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
    expose:
      - 3306

  onboarding:
    build:
      context: .
      dockerfile: OnBoarding.api/Dockerfile
    networks:
      - microservice-net
    ports:
      - 5010:80
    environment:
       ConnectionStrings__DefaultConnection: 'server=database-mysql;port=3306;database=onboarding_dev;user=root;password=password'
       LOG__LEVEL: debug
    depends_on:
      - database-mysql